#!/bin/bash

dir="/sys/class/power_supply"
ch="Charging"
#get first stats
cap0=$(cat "$dir"/BAT0/energy_now)
max0=$(cat "$dir"/BAT0/energy_full)
status=$(cat "$dir"/AC/online)

#check for second battery
cap1=$(cat "$dir"/BAT1/energy_now)&& 
	max1=$( cat "$dir"/BAT1/energy_full)&& 
	capacity=$((100*($cap0+$cap1)/($max0+$max1))) || 
	capacity=$((100*$cap0/$max0))

#get symbol for -a option and simple
if [ "$status" = "1" ] ; then symbol="🔌"; symbola=""
elif [ "$capacity" -ge 90 ] ; then symbola=""
elif [ "$capacity" -ge 60 ] ; then symbola=""
elif [ "$capacity" -ge 40 ] ; then symbola=""
elif [ "$capacity" -ge 5 ] ; then symbola=""
else symbola=""
fi
[ -z $symbol ] && symbol="🔋"

case "$1" in
	-a) echo $symbola$capacity%;;
	-s) echo BAT $capacity%;;
	-0) echo $capacity%;;
	*) echo $symbol$capacity%;;
esac
